# Use a imagem oficial do Nginx
FROM nginx:alpine

# Copiar a configuração personalizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar os arquivos estáticos
COPY static /usr/share/nginx/html/static
COPY templates /usr/share/nginx/html/templates

# Expor a porta 80
EXPOSE 80

# O Nginx já possui um CMD padrão, não precisamos especificar